version: '3'

services:
  app:
    build: .
    image: go_short_app
    container_name: go_short_app
    ports:
      - ${APP_EXPOSED_PORT:-0}:80
    working_dir: /app
    restart: always
    environment:
      - PORT=80
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=app
      - DB_USERNAME=root
      - DB_PASSWORD=secret
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7.27
    container_name: go_short_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - ${DB_EXPOSED_PORT:-0}:3306
    volumes:
      - ./docker/mysql:/var/lib/mysql
